### ISSUE TITLE
lil'bling

### ISSUE THREAD

**Issue by dazzaji** [mitmedialab/DistributedIdentity#1]
for the README.md 
![vcrop-2017-06-14-2](https://user-images.githubusercontent.com/2357755/27161914-632bd772-514c-11e7-8edb-6c0da912ae64.jpg)
![2017-06-14-1](https://user-images.githubusercontent.com/2357755/27161927-731cce34-514c-11e7-8b73-845143256a0f.jpg)
![ee391c52-3e48-482f-b681-addf1b88855d](https://user-images.githubusercontent.com/2357755/27161929-762a50ec-514c-11e7-8ba5-18309d2af6fd.jpg)
![2017-06-14](https://user-images.githubusercontent.com/2357755/27161933-7b3f4ab0-514c-11e7-869a-4699a843db55.jpg)

**Comment by schwettmann** [comment]
nah!

**Comment by dazzaji** [comment]
Would https://vimeo.com/221695929 be more conservative and professional?
